name: gh-pages-deploy

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Install cargo make
      run: cargo install cargo-make
    - name: Verify
      run: cargo make verify
    - name: Build
      run: cargo make build_release
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update gh-pages"
        branch: gh-pages
        file_pattern: pkg/*
